"""Add completed date

Revision ID: 34c3232b05d1
Revises: 046185f5bae3
Create Date: 2024-12-08 16:17:47.219849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c3232b05d1'
down_revision = '046185f5bae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_tasks', schema=None) as batch_op:
        batch_op.drop_column('completed_date')

    # ### end Alembic commands ###
